### ISSUE TITLE
Discussed Dots.Py changes (Second Set)

### ISSUE THREAD

**Issue by dpalmer9** [cbattista/OpenPsyc#25]
Heres the second change:

Change program so that it displays material different (more emphasis on communication with graphics processor)

**Comment by cbattista** [comment]
try out the new program and let me know if we are still getting the same tearing artifact

**Comment by cbattista** [comment]
switch made in https://github.com/cbattista/OpenPsyc/commit/1c989fef573cd9e7d8f79b2a1d0666405ae965b9
