### ISSUE TITLE
Check Accuracy Data For Sequential on Dots.Py

### ISSUE THREAD

**Issue by dpalmer9** [cbattista/OpenPsyc#28]
I'm not entirely sure about the sequential sections accuracy data. I also got a couple encoded negative reaction times in this presentation type. I think there is something going on with the keyboard response here. Everything else is looking reliable.

**Comment by cbattista** [comment]
-ve RTs in sequential indicate that the person hit the button before the second set of dots is shown.  So, we should code these as error as well (perhaps error type 3)

**Comment by cbattista** [comment]
OK, so I've added a new function to the accuracy grader - now a response that is too early in sequential gets a value of '3' in the ACC column.  The RTs for these responses will be negative.

done in:
https://github.com/cbattista/OpenPsyc/commit/f0fdd3cb99747529fa6e1ab3cf2dab4ae6df2464
